// layout.tsx
import type { Metadata } from "next";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "./globals.css";

import Footer from "@/components/Footer";
import HeaderWrapper from "@/components/HeaderWrapper"; // Import the new HeaderWrapper

export const metadata: Metadata = {
  title: "Fashionaura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <HeaderWrapper /> {/* Use HeaderWrapper here */}
        {children}
        <Footer />
      </body>
    </html>
  );
}